# 共轭梯度法求解线性方程组的解AX=b

In [1]:
import numpy as np
A=np.array([[3,1],[1,2]])
b=([5,5])
#A=np.array([[3,1],[1,2]])
#A=np.array([[6,3],[3,2]])
#A=np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,0,0,-1,2]])
#A=np.array([[4,3,0],[3,4,-1],[0,-1,4]]) #系数矩阵
#b=([3,5,-5]) 
#b=np.array([1,0,0,0,0])
#b=np.array([5,5])
#b=np.array([0,-1])
  
x0=np.zeros_like(b) #初始值
for i in range(1000):
    r0=b-np.dot(A,x0) #负梯度方向
    a=np.dot(r0,r0)/np.dot(np.dot(A,r0),r0) #迭代步长
    x1=a*r0+x0   #迭代后的值
    print(x1)
    if sum(np.abs(x1-x0))<1e-6:  #控制迭代次数
        break
    r1=b-np.dot(A,x1)
    x0=x1
    r0=r1
print("线性方程的解为{}".format(x0))
print("迭代次数为:{}".format(i))
print("精确解为：",(np.linalg.inv(A)).dot(b))

[1.42857143 1.42857143]
[0.95238095 1.9047619 ]
[1.02040816 1.97278912]
[0.99773243 1.99546485]
[1.00097182 1.99870424]
[0.99989202 1.99978404]
[1.00004628 1.9999383 ]
[0.99999486 1.99998972]
[1.0000022  1.99999706]
[0.99999976 1.99999951]
[1.0000001  1.99999986]
线性方程的解为[0.99999976 1.99999951]
迭代次数为:10
精确解为： [1. 2.]


# 雅可比迭代

In [39]:
import numpy as np
#A=D-L-U
#A=np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,0,0,-1,2]])
#b=np.array([1,0,0,0,0])
A=np.array([[5,2,1],[-1,4,2],[2,-3,10]])
b=np.array([-12,20,3])


D=np.zeros_like(A)
L=np.zeros_like(A)
for i in range (A.shape[0]):
    D[i,i]=A[i,i]
    print(D)
for i in range(1,A.shape[0]):
    for j in range(0,i):
        L[i,j]=-A[i,j]
        print(L)
U=D-L-A

x0=np.zeros_like(b)
for i in range(1000):
    x1=((L+U).dot(x0)+b)
    print(x1)
    x1=(1/D).dot(x1)
    x0=x1
    print(x1)
    if sum(np.abs(x1-x0))<1e-6:  #控制迭代次数
        break

print("线性方程的解为{}".format(x0))
print("迭代次数为:{}".format(i))
print("精确解为：",(np.linalg.inv(A)).dot(b))




    



[[5 0 0]
 [0 0 0]
 [0 0 0]]
[[5 0 0]
 [0 4 0]
 [0 0 0]]
[[ 5  0  0]
 [ 0  4  0]
 [ 0  0 10]]
[[0 0 0]
 [1 0 0]
 [0 0 0]]
[[ 0  0  0]
 [ 1  0  0]
 [-2  0  0]]
[[ 0  0  0]
 [ 1  0  0]
 [-2  3  0]]
[-12  20   3]
[inf nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan na

D:\Anaconda3\Anaconda3-2020.02-Windows-x86\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in true_divide
D:\Anaconda3\Anaconda3-2020.02-Windows-x86\lib\site-packages\ipykernel_launcher.py:27: RuntimeWarning: invalid value encountered in subtract



[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan 

[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan nan nan]
[nan n

In [23]:
A=np.array([[2,-1,0,0,0],[-1,2,-1,0,0],[0,-1,2,-1,0],[0,0,-1,2,-1],[0,0,0,-1,2]])
1/(A+1e-6)

array([[ 4.9999975e-01, -1.0000010e+00,  1.0000000e+06,  1.0000000e+06,
         1.0000000e+06],
       [-1.0000010e+00,  4.9999975e-01, -1.0000010e+00,  1.0000000e+06,
         1.0000000e+06],
       [ 1.0000000e+06, -1.0000010e+00,  4.9999975e-01, -1.0000010e+00,
         1.0000000e+06],
       [ 1.0000000e+06,  1.0000000e+06, -1.0000010e+00,  4.9999975e-01,
        -1.0000010e+00],
       [ 1.0000000e+06,  1.0000000e+06,  1.0000000e+06, -1.0000010e+00,
         4.9999975e-01]])